version: '3.9'

services:
  django:
    image: socialmediaprojectdockerimage
    container_name : socialmediaprojectdockercontainer
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:      
      - .:/socialmediaproject
    build: .
    ports:
      - "8000:8000"

